export const INIT_TIMELINE = 'INIT_TIMELINE';
export const APPEND_TIMELINE = 'APPEND_TIMELINE';
export const PREPEND_TIMELINE = 'PREPEND_TIMELINE';
export const SET_CHATROOM_LIST = 'SET_CHATROOM_LIST';
